services:
  proxy:
    image: ghcr.io/whatsacomputertho/fbsim-proxy:${FBSIM_PROXY_VERSION:-v1.0.0-alpha.1}
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  api:
    image: ghcr.io/whatsacomputertho/fbsim-api:${FBSIM_API_VERSION:-v1.0.0-alpha.1}
    ports:
      - "8080:8080"
  ui:
    image: ghcr.io/whatsacomputertho/fbsim-ui:${FBSIM_UI_VERSION:-v1.0.0-alpha.1}
    ports:
      - "8081:8081"
    environment:
      - FBSIM_UI_DOMAIN=0.0.0.0
      - FBSIM_UI_PORT=8081
      - FBSIM_API_HOST=http://localhost:8080