services:
  proxy:
    image: ghcr.io/whatsacomputertho/fbsim-proxy:${FBSIM_PROXY_VERSION:-v1.0.0-alpha.2}
    ports:
      - 443:443
      - 80:80
    environment:
      - FBSIM_DOMAIN=${FBSIM_DOMAIN:-whatsacomputertho.com}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
  api:
    image: ghcr.io/whatsacomputertho/fbsim-api:${FBSIM_API_VERSION:-v1.0.0-alpha.5}
    ports:
      - "8080:8080"
  ui:
    image: ghcr.io/whatsacomputertho/fbsim-ui:${FBSIM_UI_VERSION:-v1.0.0-alpha.2}
    ports:
      - "8081:8081"
    environment:
      - FBSIM_UI_DOMAIN=0.0.0.0
      - FBSIM_UI_PORT=8081
      - FBSIM_API_HOST=${FBSIM_HOST:-https://whatsacomputertho.com}