apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Values.metadata.name }}-redirect-https"
  namespace: "{{ .Values.metadata.namespace }}"
spec:
  redirectScheme:
    scheme: https
    permanent: true
